### ISSUE TITLE
Cannot open sheets or docs on Mac

### ISSUE THREAD

**Issue by flaxton** [alexkim205/Google-Drive-Desktop#26]
Google Drive Desktop launches fine, shows Google Drive view, so far, so good.

I double-click on a sheet and nothing happens. I right-click and select Open WIth | Google Sheets and...

still nothing.

So this is no good for me.

This is on macOS 10.13 High Sierra. Google Chrome (up-to-date) is the default web browser.

I see what is going on now.

I opened GDD and it had my default (personal) account. I clicked on my profile picture (top right) to switch to my G Suite work account. Logged in and it opened in a second window.

I can launch Docs or Sheets within the first window (personal account) just fine, but that's not what I wanted.

I cannot launch Docs or Sheets in the second (work account) window.

No problem, I'll just close the first (personal account) window. Except it won't close:

![Screen Shot 2020-05-16 at 9 28 02 AM](https://user-images.githubusercontent.com/1243227/82120964-9a9ab300-9757-11ea-903c-bf9cf72c6c46.png)

So I cannot use this on my work account, which is what I wanted it for :-/

**Comment by flaxton** [comment]
So I can use it in the *first* window/account but not the second. And there is no way to switch the order, since you can't close a window. GDD will Quit when you ask, but you cannot close a window.

**Comment by alexkim205** [comment]
Hey @flaxton thanks for being patient. #27 looks like a duplicate, and the problem with closing the window has been merged into `master`. The newest release `0.2.2` should fix these issues + a lot more. Hang tight, I'll deploy the release by the end of today.

**Comment by alexkim205** [comment]
Version 0.3.1 is out. Using the latest version will fix your issue. Thanks for being patient!
